application: thecraftoftea
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico
- url: /images
  static_dir: images
- url: /resources
  static_dir: resources

- url: /admin/api/.*
  script: api.app
  login: admin
- url: /admin/tools/([^/]+)
  static_files: admin/\1.html
  upload: admin/([^/]+).html
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

builtins:
- deferred: on