application: thecraftoftea
version: admin
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico
- url: /images
  static_dir: images
- url: /resources
  static_dir: resources

# tools pages
- url: /([^/]+)
  static_files: tools/\1.html
  upload: tools/([^/]+).html
  login: admin

# api handlers
- url: /([^/]+)/([^/]+)
  script: main.app
  login: admin

# default page
- url: .*
  static_files: urls.html
  upload: urls.html
  login: admin





libraries:
- name: webapp2
  version: "2.5.1"

builtins:
- deferred: on